name: CI

on:
  push:
    branches: ['*']
  release:
    types: [created]

jobs:
  test-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python versions
        uses: actions/setup-python@v2
        with:
          python-versions: [3.7, 3.8]
      - name: Install dependencies
        run: |
          pip install tox
      - name: Install loggingredactor
        run: |
          pip install -e .
      - name: Run pytest
        run: tox -e py38

  test-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install tox
      - name: Install loggingredactor
        run: |
          pip install -e .
      - name: Run flake8
        run: tox -e flake8

  testpypi-package:
    if: github.event_name == 'release' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
    needs: [test-pytest, test-flake8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get release version
        id: get_release
        run: |
          VERSION=$(echo '${{ github.event.release.tag_name }}')
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install twine wheel
      - name: Build package
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          rm -f dist/*
          python setup.py sdist bdist_wheel
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: twine upload --repository testpypi dist/*

  pypi-package:
    if: github.event_name == 'release' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [test-pytest, test-flake8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Get release version
        id: get_release
        run: |
          VERSION=$(echo '${{ github.event.release.tag_name }}')
          echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Install dependencies
        run: pip install twine wheel
      - name: Build package
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          rm -f dist/*
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: twine upload dist/*
