name: CI

on:
  push:
    branches: ['*']
  release:
    types: [created]

jobs:
  test-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install tox
      - name: Install loggingredactor
        run: |
          pip install -e .
      - name: Run pytest
        run: tox -e py37

  test-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install tox
      - name: Install loggingredactor
        run: |
          pip install -e .
      - name: Run flake8
        run: tox -e flake8

  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git config
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
      - name: Get version from setup.py
        id: get_version
        run: echo "::set-output name=version::$(python setup.py --version)"
      - name: Create tag
        run: |
          git tag -a ${{ steps.get_version.outputs.version }} -m "Version created by GitHub Actions"
          git push origin ${{ steps.get_version.outputs.version }}

  testpypi-package:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install twine wheel
      - name: Build package
        run: |
          rm -f dist/*
          python setup.py sdist bdist_wheel
      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: twine upload --repository testpypi dist/*

  pypi-package:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: tag  # Ensure this job runs after the tag job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install twine wheel
      - name: Build package
        run: |
          rm -f dist/*
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*
